/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sidd
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;

public class bar9 extends javax.swing.JFrame {

    /**
     * Creates new form bar9
     */
    String f = bar8.r;
    static String l;
    static String h;
    public bar9() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/barcode", "root", "");
            String q = "select * from studetail where cardno='" + f + "' ";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()) {
                String e = rs.getString("rno");
                l=e;
                if (e.equals(rs.getString("rno"))) {
                    DefaultTableModel df = new DefaultTableModel(0, 0);
                    String[] col = {"LAST TRANSACTION", "BALANCE"};
                    df.setColumnIdentifiers(col);
                    t8.setModel(df);
                    String q1 = "select * from transaction where cardno='" + f + "' ";
                    Statement stmt1 = con.createStatement();
                    ResultSet rs1 = stmt.executeQuery(q1);
                    while (rs1.next()) {
                        Vector v = new Vector();
                        v.add(rs1.getString("date"));
                        v.add(rs1.getString("amo"));

                        df.addRow(v);
                    }
                    String q2 = "select * from finetype where rno='" + e + "' ";
                    Statement stmt2 = con.createStatement();
                    ResultSet rs2 = stmt.executeQuery(q2);
                    while (rs2.next()) {
                        if (e.equals(rs2.getString("rno"))) {
                            t1.setText(rs2.getString("finet"));
                            t2.setText(rs2.getString("amo"));
                           h= rs2.getString("amo");
                            t3.setText(rs2.getString("Ld"));
                        }

                    }
                }
                con.close();
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t8 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "LAST TRANSACTION", "BALANCE"
            }
        ));
        jScrollPane1.setViewportView(t8);

        jLabel1.setText("   FINE TYPE");

        jLabel2.setText("AMOUNT");

        jLabel3.setText("LAST DATE");

        b1.setText("PAYNOW");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(b1)
                .addGap(151, 151, 151))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       try
       {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/barcode","root","");
            String w=t2.getText();
             String o=t1.getText();
            String q="select * from finetype where rno='"+l+"'and finet='"+o+"'";
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery(q);
   while(rs.next())
     {
         
           String q5="delete from finetype where rno='"+l+"'and finet='"+o+"'";
            Statement stmt5 = con.createStatement();
            int rs5= stmt5.executeUpdate(q5);
            if(rs5!=0)
            {
                System.out.println("delete");
                
            
           
            String q1="select * from studetail where cardno ='"+f+"'";
            Statement stmt1=con.createStatement();
            ResultSet rs1=stmt1.executeQuery(q1);
            while(rs1.next())
            {
             if(l.equals(rs1.getString("rno")))  
             {
              String u= rs1.getString("balance"); 
              int i,j,y;
              i=Integer.parseInt(u);
              y=Integer.parseInt(h);
              j=i-y;
              if(i>y)
              {
                  j=i-y;
              String q2="Update studetail set balance='"+j+"'where cardno='"+f+"'";
               Statement stmt2=con.createStatement();
              int rs3=stmt2.executeUpdate(q2);
              if(rs3!=0)
             {
               System.out.println("INSERTED");
             }
               SimpleDateFormat sdf=new SimpleDateFormat("dd/mm/yy");
                  Date d=new Date();
                 String dt=sdf.format(d);
                 String k= "insert into  transaction values('"+f+"','"+d+"','1','"+h+"')" ;
                                     Statement stmt3=con.createStatement();
                                      int rs4 =stmt3.executeUpdate(k); 
                                        if(rs4!=0)
                            {
                                System.out.println("UPDATED");
                            }             }
             else
              {
                  
              }} else
                System.out.println("error");}}
             String q6 = "select * from studetail where cardno='" + f + "' ";
            Statement stmt6 = con.createStatement();
            ResultSet rs6 = stmt.executeQuery(q6);
            while (rs6.next()) {
                String e = rs6.getString("rno");
                l=e;
                if (e.equals(rs6.getString("rno"))) {
                    DefaultTableModel df = new DefaultTableModel(0, 0);
                    String[] col = {"LAST TRANSACTION", "BALANCE"};
                    df.setColumnIdentifiers(col);
                    t8.setModel(df);
                    String q7 = "select * from transaction where cardno='" + f + "' ";
                    Statement stmt7 = con.createStatement();
                    ResultSet rs7 = stmt.executeQuery(q7);
                    while (rs7.next()) {
                        Vector v = new Vector();
                        v.add(rs7.getString("date"));
                        v.add(rs7.getString("amo"));

                        df.addRow(v);
                    }
                    String q8 = "select * from finetype where rno='" + e + "' ";
                    Statement stmt8 = con.createStatement();
                    ResultSet rs8 = stmt.executeQuery(q8);
                    while (rs8.next()) {
                        if (e.equals(rs8.getString("rno"))) {
                            t1.setText(rs8.getString("finet"));
                            t2.setText(rs8.getString("amo"));
                           //h= rs8.getString("amo");
                            t3.setText(rs8.getString("Ld"));
                        }

                    }
                }
            }}
            con.close();
        }
        catch(Exception ex)
        {
           System.out.println(ex);
        }
       
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bar9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bar9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bar9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bar9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bar9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTable t8;
    // End of variables declaration//GEN-END:variables
}
